// <auto-generated />
namespace Obooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_quantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_quantity));
        
        string IMigrationMetadata.Id
        {
            get { return "202212181009525_added_quantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
